In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
year_start = 1998
year_end = 2018
years_iter = range(year_start,year_end)

# Read cleaned data

## MSA data

In [40]:
df = {}
for year in years_iter:
    df[year] = pd.read_csv('data/cleaned/msa_naicssector_cleanedv2_totEmploy_'+str(year)+'.csv')

## State-country data

In [36]:
df_state = {}
for year in years_iter:
    df_state[year] = pd.read_csv('data/cleaned/state_naicssector_cleanedv2_totEmploy_'+str(year)+'.csv')

# Merge data

## MSA

In [41]:
for year in years_iter:
    df[year] = df[year].set_index(['MSA','NAICS Code'],drop=True)
    
tot_empl_all = df[year_start]
for year in range(year_start+1,year_end):
    tot_empl_all = pd.merge(tot_empl_all, df[year],how='inner' ,on=['MSA','NAICS Code'],copy=False )
    #df_all.to_csv('data/draft/df_all_merge_'+str(year)+'.csv')
    
tot_empl_all = tot_empl_all.T
tot_empl_all.index = list(years_iter)

## state-country

In [37]:
for year in years_iter:
    df_state[year] = df_state[year].set_index(['State','NAICS Code'],drop=True)

tot_empl_state_all = df_state[year_start]
for year in range(year_start+1,year_end):
    tot_empl_state_all = pd.merge(tot_empl_state_all, df_state[year],how='inner' ,on=['State','NAICS Code'],copy=False )
    
tot_empl_state_all = tot_empl_state_all.T
tot_empl_state_all.index = list(years_iter)

# Calculate PPC: point percent change

## MSA

In [ ]:
tot_empl_ppc=tot_empl_all[[]].copy()
for year in range(year_start,2017):
    tot_empl_ppc['TotEmp - P.P.C. - '+str(year)+'-'+str(year+1)] = \
    100*(tot_empl_all['Total Employment - '+str(year+1)]- tot_empl_all['Total Employment - '+str(year)])/\
    tot_empl_all['Total Employment - '+str(year)]
    
tot_empl_ppc = tot_empl_ppc.T
tot_empl_ppc.index = list(range(year_start+1,2018))

## State-country

In [ ]:
tot_empl_state_ppc=df_state_all[[]].copy()
for year in range(year_start,2017):
    tot_empl_state_ppc['TotEmp - P.P.C. - '+str(year)+'-'+str(year+1)] =   100*(tot_empl_state_all['Total Employment - '+str(year+1)]-
                                                                          tot_empl_state_all['Total Employment - '+str(year)])/\
                                                                            tot_empl_state_all['Total Employment - '+str(year)]
    
tot_empl_state_ppc = tot_empl_state_ppc.T
tot_empl_state_ppc.index = list(range(year_start+1,2018))

# Calculate PPC: point percent change v2

## MSA

In [ ]:
tot_empl_ppc = tot_empl_all.diff().dropna()/tot_empl_all.shift().dropna()

## State-Country

In [ ]:
tot_empl_state_ppc = tot_empl_state_all.diff().dropna()/tot_empl_state_all.shift().dropna()

## Compare MSA data to state and country data

In [ ]:
def ppc_relative( MSA,NAICS_code ):
    return (tot_empl_ppc[ (MSA,NAICS_code) ]-tot_empl_state_ppc[ ( abbr_to_state_dict[MSA_to_state_dict[MSA]] ,NAICS_code) ],
            tot_emplppc[ (MSA,NAICS_code) ]-tot_empl_state_ppc[ ( 'United States' ,NAICS_code) ] )

In [39]:
tot_empl_state_all['Wyoming']
tot_empl_state_all['California']
tot_empl_state_all['Alabama']
tot_empl_state_all

State      United States                                                       \
NAICS Code            --        11        21        22         23       31-33
1998         108117731.0  187149.0  497849.0  682227.0  5798942.0  16946142.0
1999         110705661.0  192155.0  456645.0  667062.0  6201626.0  16659930.0
2000         114064976.0  183565.0  456128.0  655230.0  6572800.0  16473994.0
2001         115061184.0  183476.0  485565.0  654484.0  6491994.0  15950424.0
2002         112400654.0  181162.0  465775.0  648254.0  6307370.0  14393609.0
2003         113398043.0  180673.0  454550.0  675938.0  6381404.0  14132020.0
2004         115074924.0  182121.0  470280.0  634734.0  6647641.0  13821976.0
2005         116317003.0  168744.0  497272.0  633106.0  6781327.0  13667337.0
2006         119917165.0  165661.0  554333.0  614427.0  7338799.0  13631683.0
2007         120604265.0  172105.0  700887.0  622757.0  7267883.0  13320172.0
2008         120903551.0  167039.0  629271.0  639403.0  7043631.0  13096159.0
2009         114509626.0  153829.0  604653.0  641552.0  5967128.0  11632956.0
2010         111970095.0  156055.0  581582.0  638058.0  5389271.0  10862838.0
2011         113425965.0  156520.0  651204.0  639795.0  5190921.0  10984361.0
2012         115938468.0  161077.0  727626.0  641063.0  5260942.0  11192043.0
2013         118266253.0  154496.0  732186.0  638575.0  5470181.0  11276438.0
2014         121069944.0  156363.0  758971.0  637840.0  5705146.0  11424251.0
2015         124085947.0  160144.0  743660.0  639234.0  6008286.0  11605501.0
2016         126752238.0  160411.0  587017.0  638917.0  6311264.0  11590420.0
2017         128591812.0  164046.0  578098.0  644703.0  6533061.0  11721785.0

State                                                    ... Wyoming           \
NAICS Code         42       44-45      48-49         51  ...      42    44-45
1998        5885230.0  14241512.0  3462624.0  3142024.0  ...  6172.0  26975.0
1999        5972022.0  14476628.0  3627057.0  3234530.0  ...  6021.0  28136.0
2000        6112029.0  14840775.0  3790002.0  3545731.0  ...  6574.0  28285.0
2001        6142089.0  14890289.0  3750663.0  3754698.0  ...  6801.0  29408.0
2002        5860256.0  14819904.0  3581013.0  3536120.0  ...  7094.0  29180.0
2003        5863860.0  14867825.0  4067935.0  3599902.0  ...  6398.0  29420.0
2004        5907051.0  15351431.0  4098870.0  3472427.0  ...  6533.0  30057.0
2005        5968929.0  15338672.0  4168016.0  3402599.0  ...  6710.0  30186.0
2006        6030647.0  15767866.0  4306405.0  3396246.0  ...  7031.0  31683.0
2007        5964850.0  15759928.0  4395432.0  3399313.0  ...  7851.0  33066.0
2008        6165204.0  15614757.0  4438903.0  3434234.0  ...  8388.0  33235.0
2009        5827769.0  14802767.0  4159604.0  3288109.0  ...  8456.0  31960.0
2010        5598507.0  14496625.0  4011989.0  3124036.0  ...  7632.0  30608.0
2011        5626328.0  14698563.0  4106359.0  3121317.0  ...  7826.0  30100.0
2012        5776243.0  14807958.0  4233381.0  3136025.0  ...  8460.0  30193.0
2013        5908763.0  15023362.0  4287236.0  3266084.0  ...  8554.0  30004.0
2014        5966747.0  15372632.0  4406767.0  3364530.0  ...  8676.0  31749.0
2015        6076109.0  15704167.0  4616568.0  3394317.0  ...  8586.0  32372.0
2016        6110748.0  15967893.0  4729709.0  3447950.0  ...  7910.0  31157.0
2017        6115476.0  15705808.0  4866282.0  3507966.0  ...  7152.0  29298.0

State
NAICS Code    48-49      51      52       54      55      56       62       72
1998         5313.0  3627.0  6131.0   6110.0  1200.0  4684.0  23694.0  22882.0
1999         5255.0  3846.0  6826.0   6214.0  1222.0  5666.0  24481.0  23435.0
2000         5343.0  3716.0  7122.0   6313.0  1356.0  5735.0  25398.0  24242.0
2001         5656.0  3866.0  6918.0   6577.0  1147.0  6295.0  25615.0  24517.0
2002         5395.0  4167.0  7102.0   6917.0  1176.0  5777.0  26535.0  23693.0
2003         6835.0  3985.0  7183.0   7223.0   892.0  6289.0  27127.0  24686.0
2004         7606.0  4093.0  7445.0   7605.0   756.0  6587.0  27645.0  24972.0
2005         8057.0  4038.0  7108.0   7951.0   752.0  6626.0  28269.0  25765.0
2006         9074.0  4115.0  6841.0   8407.0  1141.0  7367.0  28395.0  25500.0
2007         8766.0  4311.0  6839.0   9188.0  1635.0  7890.0  29400.0  26437.0
2008         9716.0  4241.0  7882.0   9304.0  1098.0  6732.0  29705.0  28812.0
2009         9874.0  4151.0  7176.0   9322.0  1183.0  6808.0  30963.0  27607.0
2010         9115.0  3957.0  6932.0   8999.0   846.0  5862.0  31820.0  26089.0
2011        10111.0  3931.0  6824.0   8837.0  1026.0  5863.0  31600.0  26086.0
2012        10140.0  4181.0  6724.0   9095.0   907.0  6196.0  31308.0  27164.0
2013         9935.0  4139.0  6652.0   9301.0  1233.0  6485.0  32229.0  27684.0
2014        10978.0  4165.0  6670.0  10164.0  1114.0  6696.0  31867.0  28926.0
2015        11147.0  4024.0  6677.0  10113.0  1074.0  6506.0  32521.0  29305.0
2016        10332.0  3945.0  6668.0   9720.0  1063.0  6135.0  33429.0  28484.0
2017         9692.0  4047.0  6698.0   9312.0  1033.0  6680.0  32917.0  27770.0

[20 rows x 965 columns]

In [58]:
tot_empl_all[('Yuma, AZ MSA','--')]-tot_empl_all[('Yuma, AZ MSA','23')]

1998    30497.0
1999    31256.0
2000    31233.0
2001    32820.0
2002    36268.0
2003    36082.0
2004    38171.0
2005    40481.0
2006    43955.0
2007    44009.0
2008    44208.0
2009    42617.0
2010    40626.0
2011    39826.0
2012    39964.0
2013    39710.0
2014    41082.0
2015    41516.0
2016    42536.0
2017    45094.0
Name: (Yuma, AZ MSA, --), dtype: float64

In [68]:

tot_empl_all[('Yuma, AZ MSA','23')].diff().dropna()/tot_empl_all[('Yuma, AZ MSA','23')].shift().dropna()

1999    0.150914
2000   -0.023995
2001   -0.010388
2002    0.116865
2003    0.070175
2004    0.171546
2005    0.199650
2006    0.155384
2007   -0.153416
2008   -0.053237
2009   -0.206253
2010   -0.227827
2011   -0.141284
2012   -0.005128
2013    0.034794
2014    0.009132
2015   -0.010695
2016   -0.012890
2017    0.087195
Name: (Yuma, AZ MSA, 23), dtype: float64

In [67]:
tot_empl_all[('Yuma, AZ MSA','23')].shift()

1998       NaN
1999    2571.0
2000    2959.0
2001    2888.0
2002    2858.0
2003    3192.0
2004    3416.0
2005    4002.0
2006    4801.0
2007    5547.0
2008    4696.0
2009    4446.0
2010    3529.0
2011    2725.0
2012    2340.0
2013    2328.0
2014    2409.0
2015    2431.0
2016    2405.0
2017    2374.0
Name: (Yuma, AZ MSA, 23), dtype: float64

In [69]:
tot_empl_all.diff().dropna()/tot_empl_all.shift().dropna()

MSA        Abilene, TX MSA                                                    \
NAICS Code              --        21        23     31-33     44-45        52
1999              0.000227 -0.528791 -0.040067  0.069324 -0.000409  0.008524
2000              0.013254  0.293279  0.089565  0.001080 -0.014852  0.286846
2001             -0.010029  0.091339 -0.075818 -0.114679  0.035823 -0.002874
2002              0.026817  0.203463  0.296200 -0.031698  0.019228  0.090161
2003              0.142869  0.049161  0.222518  0.097576  0.109917  0.098565
2004             -0.029435  0.064000 -0.308719 -0.163178  0.019122  0.051220
2005             -0.026449  0.114930  0.146630 -0.043180 -0.005559 -0.028777
2006              0.035841  0.099229  0.147130  0.055874  0.027254  0.005387
2007              0.015028  0.293602  0.222955 -0.079715  0.017800  0.015405
2008              0.027725  0.789973 -0.048272  0.013269  0.014704  0.032982
2009             -0.029996 -0.548070  0.112255 -0.137505 -0.039851  0.006705
2010             -0.012872  0.180905 -0.006019 -0.067904 -0.036817 -0.025690
2011             -0.011427  0.163121 -0.275501  0.038462  0.013177 -0.035807
2012              0.041328  0.331707 -0.038251  0.095425 -0.007616  0.020932
2013              0.007325 -0.064103  0.004011  0.059666  0.046045 -0.033730
2014             -0.004905  0.083170 -0.002663 -0.085586 -0.002822  0.008214
2015              0.041433 -0.175700  0.473632  0.191708 -0.008036 -0.094365
2016             -0.011650 -0.473973 -0.084711 -0.021702  0.024304 -0.025112
2017             -0.015160  0.068750 -0.139322  0.011972 -0.037875 -0.006536

MSA                            Akron, OH MSA            ... Yuba City, CA MSA  \
NAICS Code        62        81            --        23  ...                62
1999        0.043724 -0.021063      0.007202 -0.144682  ...         -0.074095
2000        0.003056 -0.027938      0.041708  0.310145  ...         -0.058578
2001       -0.014053  0.021143     -0.011630 -0.016167  ...          0.001898
2002       -0.027609  0.054998     -0.031790 -0.213054  ...          0.059158
2003        0.312833  0.099356      0.035182  0.308763  ...         -0.056649
2004       -0.047080 -0.004742     -0.006124 -0.013828  ...          0.056047
2005       -0.057354 -0.021861      0.000894 -0.196367  ...          0.015363
2006        0.048848 -0.068768     -0.001394  0.038712  ...          0.061309
2007        0.003398 -0.040615     -0.004120 -0.010065  ...          0.042029
2008       -0.027337  0.001924     -0.011546 -0.022740  ...          0.017768
2009        0.007642 -0.071063     -0.053144 -0.165272  ...          0.106145
2010        0.029915  0.020331     -0.024836  0.005137  ...         -0.001105
2011       -0.006955 -0.023978      0.026456  0.030163  ...         -0.145363
2012        0.075225  0.073356      0.024469 -0.080683  ...         -0.023295
2013       -0.054866 -0.022244      0.002878 -0.038220  ...          0.071929
2014       -0.011351 -0.017145      0.021287  0.060528  ...          0.018541
2015        0.070362  0.030191      0.010457  0.051609  ...          0.010576
2016        0.000077  0.061218      0.013314  0.107390  ...          0.062446
2017       -0.008044 -0.002455     -0.005643 -0.124907  ...          0.000323

MSA                            Yuma, AZ MSA                                \
NAICS Code        72        81           --        23     31-33        42
1999       -0.040663 -0.012407     0.024888  0.150914 -0.297859 -0.101496
2000       -0.045267  0.021985    -0.000736 -0.023995  0.072551 -0.033294
2001        0.127586 -0.114935     0.050812 -0.010388 -0.001723  0.115621
2002        0.179281  0.038889     0.105058  0.116865  0.232628  1.031974
2003        0.044084  0.006016    -0.005128  0.070175  0.089286 -0.489962
2004       -0.011177 -0.035216     0.057896  0.171546  0.092253 -0.013830
2005        0.048038  0.019972     0.060517  0.199650  0.065627 -0.056634
2006        0.030857  0.021607     0.085818  0.155384 -0.015742  0.011435
2007        0.049404  0.082617     0.001229 -0.153416 -0.053311 -0.003957
2008        0.051786 -0.082418     0.004522 -0.053237 -0.068168  0.099319
2009       -0.131912 -0.085828    -0.035989 -0.206253 -0.103690  0.054724
2010       -0.013042 -0.066230    -0.046718 -0.227827 -0.079134  0.069016
2011        0.052243 -0.095090    -0.019692 -0.141284  0.013102  0.076923
2012       -0.023072 -0.041344     0.003465 -0.005128  0.009509  0.036139
2013        0.010164  0.027853    -0.006356  0.034794  0.139789  0.003693
2014        0.066884  0.024476     0.034550  0.009132  0.141488 -0.251840
2015       -0.012760 -0.013652     0.010564 -0.010695 -0.018245  0.027869
2016        0.027536  0.044118     0.024569 -0.012890 -0.078466  0.069644
2017       -0.051955  0.035626     0.060137  0.087195  0.231754  0.114811

MSA
NAICS Code     44-45        52        54
1999        0.026633  0.032120  0.039052
2000        0.031655 -0.013485  0.079195
2001        0.059123  0.019979  0.073383
2002       -0.073205 -0.114433  0.128621
2003        0.017841  0.045402  0.064682
2004        0.051536  0.055679  0.170685
2005        0.184784  0.070675 -0.046952
2006        0.083935  0.022660  0.120138
2007       -0.016863  0.075145  0.070988
2008        0.010833  0.087814 -0.080692
2009       -0.072003  0.135091 -0.087774
2010       -0.057861 -0.082729  0.042955
2011       -0.005873 -0.082278 -0.005766
2012       -0.042255  0.112931  0.120133
2013        0.048947 -0.047250 -0.035503
2014        0.047558 -0.065854  0.052914
2015        0.012204 -0.040905  0.012382
2016       -0.003858 -0.079855 -0.100719
2017       -0.017671  0.218935 -0.012800

[19 rows x 2634 columns]